sudo: required

services: docker

before_install:
  - docker-compose up --build -d

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test